export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Beinhaltet", value: "iLike" as const },
    { label: "Beinhaltet nicht", value: "notILike" as const },
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist kleiner als", value: "lt" as const },
    { label: "Ist kleiner als oder gleich", value: "lte" as const },
    { label: "Ist größer als", value: "gt" as const },
    { label: "Ist größer als oder gleich", value: "gte" as const },
    { label: "Ist zwischen", value: "isBetween" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist vor", value: "lt" as const },
    { label: "Ist nach", value: "gt" as const },
    { label: "Ist an oder vor", value: "lte" as const },
    { label: "Ist an oder nach", value: "gte" as const },
    { label: "Ist zwischen", value: "isBetween" as const },
    { label: "Ist relativ zu heute", value: "isRelativeToToday" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Beinhaltet", value: "inArray" as const },
    { label: "Beinhaltet nicht", value: "notInArray" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
  ],
  sortOrders: [
    { label: "Aufsteigend", value: "asc" as const },
    { label: "Absteigend", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};

export type Operators = (typeof dataTableConfig)["operators"][number];